### ISSUE TITLE
Flexibility with raylib-d:install.

### ISSUE THREAD

**Issue by Cyrodwd** [Kapendev/parin#1]
In the source code of ‘popka:setup’, it runs ‘raylib-d:install’ directly, without prompting the user to do so.
For those who want to place the raylib linkers manually or literally do not use systems like Windows, Mac or Linux (a very obvious example is FreeBSD), you can choose not to run raylib-d:install in ‘setup’.

It's more of an idea than a bug.

**Comment by Kapendev** [comment]
The script could accept a `nolibs` argument maybe.

**Comment by Kapendev** [comment]
@Cyrodwd I change it now and you can pass `N` or `n` to disable `raylib-d:install`.
If you don't pass anything, it will ask you to choose.

**Comment by Kapendev** [comment]
Let me know if something does not work.
